### PR TITLE
More parent POM improvements

### PR DESCRIPTION
**Pull request by ctubbsii**
- Adds Apache License header
- Update URLs and description
- Add inceptionYear (for ASF)
- Update mailingLists
- Add prerequisites
- Remove unnecessary versions, and update specified plugins
- Use Java 8 by default
- Remove unnecessary properties defined in ASF pom
- Add git hash to jar manifests
- Update enforcer rules for java and maven
- Update javadoc configuration for Java 8
- Add release plugin configuration

### CODE REVIEW

**Comment by keith-turner** [comment]
@ctubbsii  did you try doing a test release with these changes?

**Comment by ctubbsii** [comment]
I tried, but it looks like we don't have a staging profile on Nexus yet. See https://issues.apache.org/jira/browse/INFRA-12254

**Comment by ctubbsii** [comment]
We now have a staging profile on Nexus, and I've successfully tested deploying to a staging repository.

**Comment by ctubbsii** [comment]
I'm going to push this and apache/incubator-fluo#698

**Pull request closed without merging**
